services:
  app:
    build: .
    container_name: supplycart_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - '8000:8000'
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql
    container_name: supplycart_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: supplycart
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
